feat!: add mint pool address for mint module
cosmosquad-labs/squad pull request #316
Opened 2022-05-19 10:51 UTC by dongsam

## Description

closes: #314 

## Tasks

- [ ] 

## References

- 

---

Before we can merge this PR, please make sure that all the following items have been
checked off. If any of the checklist items are not applicable, please leave them but
write a little note why.

- [ ] Appropriate labels applied
- [ ] Targeted PR against correct branch
- [ ] Linked to Github issue with discussion and accepted design OR link to spec that describes this work.
- [ ] Code follows the [module structure standards](https://github.com/cosmos/cosmos-sdk/blob/master/docs/building-modules/structure.md).
- [ ] Wrote unit and integration
- [ ] Updated relevant documentation (`docs/`) or specification (`x/<module>/spec/`)
- [ ] Added relevant `godoc` [comments](https://go.dev/blog/godoc).
- [ ] Re-reviewed `Files changed` in the Github PR explorer
- [ ] Review `Codecov Report` in the comment section below once CI passes

2022-05-24 04:45 UTC, kogisin approved these changes
LGTM

2022-05-29 12:55 UTC, hallazzang requested changes

2022-05-29 12:57 UTC, hallazzang requested changes

2022-05-29 12:57 UTC, hallazzang commented on x/mint/spec/04_params.md
> +MintPoolAddress is the account address where the inflation generated by the mint module will accumulate. The default is FeeCollector, but if it set FeeCollector, it could mix the minted inflation wit
```suggestion
MintPoolAddress is the account address where the inflation generated by the mint module will accumulate. The default is FeeCollector, but if it set to FeeCollector, minted inflation could be mixed together with collected tx fees. Therefore, it is recommended to specify a separate address depending on the chain and staking reward can be sent to the FeeCollector through Budget module functionality
```

// mint_pool_address defines the address where inflation will be minted. The default is FeeCollector,
  // but if it is set to FeeCollector, minted inflation could be mixed together with collected tx fees.

2022-05-31 04:43 UTC, hallazzang approved these changes
LGTM

2022-05-31 07:43 UTC, merged