feat: add marketmaker module
cosmosquad-labs/squad pull request #321
Opened 2022-06-27 08:19 UTC by dongsam

## Description

closes: #320 

## Tasks

- [ ] spec poc
- [ ] skeleton
- [ ] core logics
- [ ] proposal
- [ ] test codes

## References

- 

---

Before we can merge this PR, please make sure that all the following items have been
checked off. If any of the checklist items are not applicable, please leave them but
write a little note why.

- [ ] Appropriate labels applied
- [ ] Targeted PR against correct branch
- [ ] Linked to Github issue with discussion and accepted design OR link to spec that describes this work.
- [ ] Code follows the [module structure standards](https://github.com/cosmos/cosmos-sdk/blob/master/docs/building-modules/structure.md).
- [ ] Wrote unit and integration
- [ ] Updated relevant documentation (`docs/`) or specification (`x/<module>/spec/`)
- [ ] Added relevant `godoc` [comments](https://go.dev/blog/godoc).
- [ ] Re-reviewed `Files changed` in the Github PR explorer
- [ ] Review `Codecov Report` in the comment section below once CI passes

2022-08-30 02:42 UTC, kogisin requested changes
Great work on adding `marketmaker` module overall! I left some suggestions and comments below. Some of the comments are very nitpicking, so it is okay to ignore them if you don't like.

2022-08-30 02:42 UTC, kogisin commented on x/marketmaker/keeper/marketmaker.go
> +	}
I think we can avoid using `GetAllBalances` if `totalAmt` is empty.
```suggestion
	if !totalAmt.Empty() {
		reserveBalance := k.bankKeeper.GetAllBalances(ctx, types.DepositReserveAcc)
		if reserveBalance.IsAllLT(totalAmt) {
			return fmt.Errorf("DepositReserveAcc differs from the actual value; have %s, want %s", reserveBalance, totalAmt)
		}
	}
```

2022-08-30 02:42 UTC, kogisin commented on x/marketmaker/keeper/marketmaker.go
> +	}
I think we can avoid using `GetAllBalances` if `totalClaimable` is empty. Same suggestion as above comment.

2022-08-30 02:42 UTC, kogisin commented on x/marketmaker/keeper/proposal_handler.go
> +}
I see that the function names are following the actual field names in `MarketMakerProposal`, but I think it is better to follow general naming convention by starting the function name with verb.

- IncludeMarketMakers
- DistributeMarketMakerIncentives
- ExcludeMarketMakers
- RejectMarketMakers

2022-08-30 02:42 UTC, kogisin commented on x/marketmaker/keeper/proposal_handler.go
> +		}
Should we remove the comment `// pass already eligible market maker`? I think the comment refers to use `continue` here to pass already eligible market maker, but it actually returns an error.

2022-08-30 02:42 UTC, kogisin commented on x/marketmaker/keeper/proposal_handler.go
> +		k.DeleteDeposit(ctx, mmAddr, p.PairId)
Since this logic is used in `RejectionMarketMakers` function as well, I recommend to create a separate function to handle.

2022-08-30 02:42 UTC, kogisin commented on x/marketmaker/keeper/proposal_handler.go
> +	}
Remove the unnecessary space in between two brackets (Very minor stuff)
```suggestion
		}
	}
```

2022-08-30 02:42 UTC, kogisin commented on x/marketmaker/keeper/proposal_handler.go
> +	}
This logic can be shortened with the following suggestion.
```suggestion
	for _, p := range proposals {
                incentive, found := k.GetIncentive(ctx, p.GetAccAddress())
		if !found {
			incentive.Claimable = sdk.Coins{}
		}
		k.SetIncentive(ctx, types.Incentive{
			Address:   p.Address,
			Claimable: incentive.Claimable.Add(p.Amount...),
		})
	}
```

2022-08-30 02:42 UTC, kogisin commented on x/marketmaker/client/cli/tx.go
> +}
I suggest to format the JSON
```suggestion
{
  "title": "Market Maker Proposal",
  "description": "Are you ready to market making?",
  "inclusions": [
    {
      "address": "cosmos1vqac3p8fl4kez7ehjz8eltugd2fm67pckpl7pn",
      "pair_id": "1"
    }
  ],
  "exclusions": [],
  "rejections": [
    {
      "address": "cosmos1vqac3p8fl4kez7ehjz8eltugd2fm67pckpl7pn",
      "pair_id": "2"
    }
  ],
  "distributions": [
    {
      "address": "cosmos1vqac3p8fl4kez7ehjz8eltugd2fm67pckpl7pn",
      "pair_id": "1",
      "amount": [
        {
          "denom": "stake",
          "amount": "100000000"
        }
      ]
    }
  ]
}
```

2022-08-30 02:42 UTC, kogisin commented on x/marketmaker/client/cli/tx.go
> +for each pair, the params.deposit_amount will be deposited, which will be refunded when included or rejected as a market maker through proposal
```suggestion
Apply to be a market maker for a number of pairs. The deposit amount defined in params is required to deposit, and the amount is expected to be refunded when you are either included or rejected by the community (through a governance proposal).
```

2022-08-30 02:42 UTC, kogisin commented on x/marketmaker/client/cli/tx.go
> +Example:
Very minor stuff. To align with the other commands, I suggest to have a space in between.
```suggestion
Claim all market making incentives distributed through governance

Example:
```

2022-08-31 04:47 UTC, kogisin approved these changes
LGTM

2022-08-31 09:56 UTC, merged

2022-09-01 05:58 UTC, hallazzang reviewed
LGTM overall, requesting some changes.

2022-09-01 05:58 UTC, hallazzang commented on x/marketmaker/client/cli/query.go
> +	farmingQueryCmd := &cobra.Command{
Should rename `farmingQueryCmd` to `marketmakerQueryCmd` or similar.

2022-09-01 05:58 UTC, hallazzang commented on x/marketmaker/client/cli/query.go
> +func GetQueryMarketMakerCmd() *cobra.Command {
Name suggestion: `GetCmdQueryMarketMakers`

2022-09-01 05:58 UTC, hallazzang commented on x/marketmaker/client/cli/query.go
> +		Use:   "marketmaker",
Suggestion: `"marketmakers"` since the original query method is named `MarketMakers` and it returns a list.

2022-09-01 05:58 UTC, hallazzang commented on x/marketmaker/client/cli/tx.go
> +			}
How about passing `cobra.ExactArgs(1)` for `Args` field instead of checking the length of `args`?

2022-09-01 05:58 UTC, hallazzang commented on x/marketmaker/keeper/marketmaker.go
> +		if reserveBalance.IsAllLT(totalAmt) {
Use `!totalAmt.IsAllGTE(totalAmt)`(effectively `reserveBalance.IsAnyLT(totalAmt)` but the method doesn't exist).

2022-09-01 05:58 UTC, hallazzang commented on x/marketmaker/keeper/marketmaker.go
> +		if reserveBalance.IsAllLT(totalClaimable) {
Same suggestion as above applies here.

2022-09-01 05:58 UTC, hallazzang commented on x/marketmaker/simulation/decoder.go
> +			panic(fmt.Sprintf("invalid farming key prefix %X", kvA.Key[:1]))
`farming` -> `marketmaker`

2022-09-01 05:58 UTC, hallazzang commented on x/marketmaker/spec/06_params.md
> +<!-- order: 7 -->
`order: 6`

2022-09-01 05:58 UTC, hallazzang commented on x/marketmaker/spec/05_events.md
> +<!-- order: 6 -->
`order: 5`

2022-09-01 05:58 UTC, hallazzang commented on x/marketmaker/spec/07_proposal.md
> +<!-- order: 8 -->
`order: 7`

2022-09-01 07:32 UTC, dongsam commented
@hallazzang Thanks for the review, all of the suggestions applied on https://github.com/cosmosquad-labs/squad/pull/353

2022-09-01 07:34 UTC, hallazzang commented on x/marketmaker/keeper/marketmaker.go
> +		if reserveBalance.IsAllLT(totalAmt) {
Oh, that was my mistake. You're right.